---
- name: Check Automox Agent service
  hosts: all
  gather_facts: false

  vars:
    service_name: amagent.service

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Fail if Automox Agent service is missing
      ansible.builtin.fail:
        msg: "Automox Agent service is missing"
      when: service_name not in ansible_facts.services

    - name: Fail if Automox Agent service is not running
      ansible.builtin.fail:
        msg: "Automox Agent service exists but is not running"
      when: ansible_facts.services[service_name].state != "running"